name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run hooks
      run: .hooks/autohook.sh run-hook pre-commit rs
    - name: Generate coverage report
      run: |
        apt-get update && apt-get install libssl-dev pkg-config cmake zlib1g-dev
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cobertura.xml
